services:
  - type: web
    name: back-bidnow
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash scripts/render_start.sh
    autoDeploy: true
