# Generated by Django 5.2.8 on 2026-03-28 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('titular', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Subasta',
            fields=[
                ('id_subasta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='subasta', to='core.producto')),
                ('subastador', models.ForeignKey(blank=True, db_column='id_subastador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subastas', to='core.usuario')),
            ],
            options={
                'db_table': 'subasta',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('monto_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.ForeignKey(blank=True, db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacciones', to='core.metodopago')),
                ('subasta', models.OneToOneField(db_column='id_subasta', on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaccion', to='core.subasta')),
                ('ganador', models.ForeignKey(blank=True, db_column='id_ganador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacciones_ganadas', to='core.usuario')),
            ],
            options={
                'db_table': 'transaccion',
            },
        ),
        migrations.CreateModel(
            name='Puja',
            fields=[
                ('id_puja', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('subasta', models.ForeignKey(db_column='id_subasta', on_delete=django.db.models.deletion.CASCADE, related_name='pujas', to='core.subasta')),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pujas', to='core.usuario')),
            ],
            options={
                'db_table': 'puja',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='vendedor',
            field=models.ForeignKey(db_column='id_vendedor', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.usuario'),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='core.usuario'),
        ),
    ]
