"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import parse_qsl, unquote, urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-829of5fltv64j1!z3idbvqog+n+oa#rw@twp5m8iyx_@9ke=6u",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS if h.strip()]
# En Render existe la variable de entorno RENDER; `.onrender.com` autoriza tu servicio (ej. back-bidnow.onrender.com).
if os.environ.get("RENDER") and ".onrender.com" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(".onrender.com")

def _csv_urls(name: str, default: str = "") -> list[str]:
    return [x.strip() for x in os.getenv(name, default).split(",") if x.strip()]


CSRF_TRUSTED_ORIGINS = _csv_urls("CSRF_TRUSTED_ORIGINS")
_render_url = os.getenv("RENDER_EXTERNAL_URL", "").strip().rstrip("/")
if _render_url and _render_url not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_render_url)

# Front Static Site (Render) + Vite local. URLs exactas, sin comodines (CORS/CSRF).
# https://front-bidnow.onrender.com — sitio publico del front en Render.
_FRONT_STATIC_RENDER = "https://front-bidnow.onrender.com"
_FRONT_LOCAL_VITE = ("http://localhost:5173", "http://127.0.0.1:5173")

FRONTEND_ORIGINS = _csv_urls("FRONTEND_ORIGINS")
if os.environ.get("RENDER"):
    for _u in (_FRONT_STATIC_RENDER, *_FRONT_LOCAL_VITE):
        if _u not in FRONTEND_ORIGINS:
            FRONTEND_ORIGINS.append(_u)
elif DEBUG:
    for _u in _FRONT_LOCAL_VITE:
        if _u not in FRONTEND_ORIGINS:
            FRONTEND_ORIGINS.append(_u)
for _origin in FRONTEND_ORIGINS:
    if _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)

# Render (reverse proxy): sin esto el admin puede fallar (CSRF / cookies / is_secure).
if os.environ.get("RENDER"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
    # Origen del propio backend (login POST /admin); RENDER_EXTERNAL_URL a veces vacío en build.
    _render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME", "").strip()
    if _render_host:
        _api_origin = f"https://{_render_host}".rstrip("/")
        if _api_origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_api_origin)
    if not DEBUG:
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True

CORS_ALLOWED_ORIGINS = list(FRONTEND_ORIGINS)
CORS_ALLOW_CREDENTIALS = os.getenv("CORS_ALLOW_CREDENTIALS", "").lower() in (
    "1",
    "true",
    "yes",
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Si existe DATABASE_URL (Render Postgres), se parsea completa:
# OPTIONS se arma desde el querystring (ej. sslmode=require).


def _management_cmd_allows_short_pg_host() -> bool:
    """collectstatic (build en Render) no usa la BD; no bloquear import de settings."""
    if len(sys.argv) < 2:
        return False
    return sys.argv[1] in {
        "collectstatic",
        "findstatic",
        "makemigrations",
        "compilemessages",
    }


def _normalize_postgres_host(host: str) -> str:
    """Render a veces muestra solo `dpg-xxxxx-a` (sin dominio); el DNS público no lo resuelve."""
    host = (host or "").strip()
    if not host or "." in host or not host.startswith("dpg-"):
        return host
    suffix = os.getenv("DATABASE_HOST_SUFFIX", "").strip()
    if suffix:
        if not suffix.startswith("."):
            suffix = "." + suffix
        return host + suffix
    # En Render suele pegarse el host corto del dashboard; el FQDN público es host + región.
    if os.environ.get("RENDER"):
        if _management_cmd_allows_short_pg_host():
            return host
        default = os.getenv(
            "RENDER_DEFAULT_PG_HOST_SUFFIX",
            ".oregon-postgres.render.com",
        ).strip()
        if default:
            if not default.startswith("."):
                default = "." + default
            return host + default
    return host


def _database_from_env() -> dict:
    raw_url = os.getenv("DATABASE_URL", "").strip()
    if raw_url:
        if raw_url.startswith("postgres://"):
            raw_url = "postgresql://" + raw_url[len("postgres://") :]
        tmp = urlparse(raw_url)
        db_name = (tmp.path or "").lstrip("/").split("?")[0]
        options = dict(parse_qsl(tmp.query))
        host = _normalize_postgres_host(tmp.hostname or "")
        # Render Postgres externo exige TLS; si DATABASE_URL no trae ?sslmode=..., la conexión falla.
        require_ssl = os.getenv("DB_SSL_REQUIRE", "").lower() in (
            "1",
            "true",
            "yes",
        ) or (host and ".render.com" in host)
        if require_ssl:
            options.setdefault("sslmode", "require")
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": db_name,
            "USER": unquote(tmp.username) if tmp.username else "",
            "PASSWORD": unquote(tmp.password) if tmp.password else "",
            "HOST": host,
            "PORT": tmp.port or 5432,
            "OPTIONS": options,
        }

    host = _normalize_postgres_host(os.getenv("DB_HOST", "localhost"))
    port = os.getenv("DB_PORT", "5432")
    require_ssl = os.getenv("DB_SSL_REQUIRE", "").lower() in (
        "1",
        "true",
        "yes",
    ) or (host and ".render.com" in host)
    options = {"sslmode": "require"} if require_ssl else {}

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "subastas"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD")
        or os.getenv("POSTGRES_PASSWORD")
        or "",
        "HOST": host,
        "PORT": port,
        "OPTIONS": options,
    }


DATABASES = {"default": _database_from_env()}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = os.getenv("TIME_ZONE", "America/Bogota")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

DATA_UPLOAD_MAX_MEMORY_SIZE = 20971520  # 20 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Logs en consola (Render / Gunicorn): sin esto suele verse solo "GET ... 500" sin el motivo.
_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": _LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": _LOG_LEVEL,
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # Sin SessionAuthentication: Swagger UI puede usar POST/PUT/DELETE sin CSRF en local.
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "API Subastas",
    "DESCRIPTION": (
        "CRUD sobre las tablas existentes (usuario, método de pago, producto, "
        "subasta, puja, transacción). Documentación OpenAPI 3 y Swagger UI."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
